### ISSUE TITLE
Define severity levels for incident types

### ISSUE THREAD

**Issue by MattJKTaylor** [GPIG-Group-C/web-server-ui#45]
What are the different severity levels for fire, gas etc.
(See Google doc table)

**Comment by lpaskaleva** [comment]
When added by the system all icons will be with the highest severity and after human assessment (update from the app) their severity can be changed. => for the demo we will need different severity levels only for the fire icon (the ones that you defined seem to be sufficient). 

Furthermore, for the demo, only the fire icon needs to be clickable and consequently, it will be the only one which can be updated => the update window can have only the predefined severity values for fire (Fire Extinguished/Fire Contained/Fire Escalating)

Hope that answers your question.

PS Please message me, when you create tickets assigned to me ;d

**Comment by lpaskaleva** [comment]
Correction: the blocked road marker should also be clickable, but still doesn't need additional severity values because it will not be updated.

**Comment by MattJKTaylor** [comment]
Great thanks I'll update it during our meeting tomorrow
