### ISSUE TITLE
Fix red dots on map

### ISSUE THREAD

**Issue by MikeODowd** [GPIG-Group-C/web-server-ui#56]

**Comment by MikeODowd** [comment]
Red dots appear on buildings if you zoom in far enough

**Comment by sib506** [comment]
<img width="1346" alt="screen shot 2018-05-24 at 13 58 23" src="https://user-images.githubusercontent.com/7630332/40486969-a991300a-5f5a-11e8-8049-d399be2f7b21.png">

**Comment by RB1038** [comment]
Map styling JSON updated due to new team requirements. Red dots removed, as JSON is now valid
